### ISSUE TITLE
Clarify code standards in the docs

### ISSUE THREAD

**Issue by Ostrzyciel** [Kaszanas/SC2DatasetPreparator#34]
In CONTRIBUTING I don't see any mention of code standards or pre-commit checks (which I know are implemented). This should be at least briefly explained there, in particular how to run the pre-commit checks.

**Comment by Ostrzyciel** [comment]
It's not clear for me what pre-commit-checks are there currently :D I didn't dig too deep into this. But, they pass in the CI, so I would consider them "sane".

**Comment by Kaszanas** [comment]
Solved in #39
